# Simple Configuration for Commodity Forecasting System
system:
  device: "cuda"
  num_workers: 4
  seed: 42
  log_level: "INFO"
  experiment_name: "commodity_forecasting"

data:
  raw_path: "data/raw"
  train_file: "train.csv"
  test_file: "test.csv"
  target_pairs_file: "target_pairs.csv"
  train_labels_file: "train_labels.csv"

patches:
  window_sizes: [7, 14]
  strides: [7]
  embedding_dim: 64
  patch_size: 7
  max_patches_per_series: 100

knowledge_graph:
  db_path: "database/commodity_kg.db"
  correlation_threshold: 0.3
  p_value_threshold: 0.05
  max_correlations_per_node: 50
  cache_size: 1000
  max_retrieval_nodes: 50
  max_retrieval_edges: 100
  similarity_threshold: 0.2

model:
  d_model: 128
  n_heads: 8
  n_layers: 6
  d_ff: 512
  dropout: 0.1
  max_seq_len: 256
  context_dim: 64
  context_heads: 4
  use_peft: true
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  num_horizons: 4
  output_dim: 1

training:
  batch_size: 32
  learning_rate: 1e-4
  num_epochs: 100
  warmup_steps: 1000
  optimizer: "adamw"
  weight_decay: 0.01
  scheduler: "cosine"
  val_split: 0.2
  early_stopping_patience: 10
  save_best_only: true
  loss_function: "mse"

inference:
  batch_size: 64
  use_graphrag: true
  context_length: 50
  output_path: "outputs/predictions.csv"
  submission_format: "kaggle"
  max_inference_time: 3600
